name: Deploy Astro to VPS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/Projects/funky-portfolio
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh    
          git pull origin main
          npm install --only=prod
          npm run build --if-present
          cp -r ~/Projects/funky-portfolio/dist/* /var/www/arttu.pro/html/
